import torch 

class cma_es:
    '''
    solving an inverse problem through stochastic optimization 
    the opitmizaiton algorithm here is cma es- see below for explanation and source
    true_output is what we are trying to learn,
    system is the map from input to output

    bench_mark_loss is the loss than needs to be achieved
    n_best_samples - generate the next generation from the n_best_samples
    with the lowest losses in current generation

    for weight_function see cma
    '''
    def __init__(self, 
                 true_output, 
                 loss, 
                 system, 
                 n_split,
                 bench_mark_loss,
                 n_best_samples,
                 n_samples_next_gen,
                 weight_function
                ):
        
        self.true_output = true_output
        self.loss = loss
        self.system = system
        self.n_split = n_split 
        self.bench_mark_loss = bench_mark_loss
        self.n_best_samples = n_best_samples
        self.n_samples_next_gen = n_samples_next_gen
        self.weight_function = weight_function

    def run_optimization(self, 
                         initial_inputs, 
                         initial_outputs
                         ):
        '''
        its assumed that you have a starting randomly generated dataset
        for example the one generated by moment_class
        '''
        
        achieved_loss = float('inf')

        inputs = initial_inputs
        losses = self.loss( initial_outputs, self.true_output)

        best_inputs, best_losses = self.best_n(inputs, losses)

        while ( achieved_loss > self.bench_mark_loss ) :
            inputs, losses = self.previous_inputs_to_next(self, 
                                                          best_inputs, 
                                                          best_losses
                                                          )
            
            achieved_loss = min(losses)

        achieved_index = losses.index(achieved_loss)
        return inputs(achieved_index)
       
    def previous_inputs_to_next(self, 
                                inputs_previous, 
                                losses_previous, 
                                ):
        

        
        inputs = self.cma(inputs_previous, 
                                  losses_previous, 
                                  self.n_samples_next_gen
                                  )
        
        inputs_split = torch.split( inputs, 
                                       self.split, 
                                       dim=0 
                                       )
        
        outputs = []

        for input_batch in inputs_split :
            output_batch = self.system( input_batch )
            outputs.append(output_batch)

        outputs = torch.stack( outputs, dim=0 )
        losses = self.loss(outputs, self.true_output )

        return self.best_n( inputs, losses)
    
    def best_n( self, inputs, losses ):

        best_losses, best_indices = torch.topk(losses, 
                                                k=self.n_best_samples,
                                                largest = False)
        best_inputs = inputs[best_indices]

        return best_inputs, best_losses
        
    def cma(self, 
            inputs, 
            losses, 
            ):
        
        '''
        cma just takes previous stage data,
        and uses a chosen weighting system  
        to generate modified mean and variances of the data
        these then are used as inputs to a normal distribution
        to generate next generation
        source:
        https://arxiv.org/pdf/1604.00772

        '''  

        losses = losses.unsqueeze(1)   #shape: (num,dim)

        weights = self.weight_function(losses)
        weights = weights / weights.sum()

        #taking weighted mean
        offset_w_mean = torch.sum( inputs * weights, dim = 0 ) #shape (dim)

        #covariance matrix accoring to source, equation 12
        input_mean = torch.mean( inputs, dim = 0 ) 
        unbiased_input = (inputs - input_mean).unsqueeze(2) #shape (num,dim,1)
        unbiased_input_t = unbiased_input.transpose(1,2) #shape (num,1,dim)
        # |dim,1><1,dim| = dim,dim
        cov_elements = unbiased_input @ unbiased_input_t #shape (num,dim,dim)

        weights = weights.unsqueeze(1)
        cov = torch.sum(weights*cov_elements, dim = 0 ) #shape (dim,dim)

        #now sampling from a normal
        z = torch.randn(self.no_samples_next_gen, self.dim)

        # and we use cholesky decomp to shape correct (LL^T = cov)
        L = torch.linalg.cholesky(cov)
        samples_out = offset_w_mean + z @ L.T

        return samples_out
    

  
