import torch 

'''
solving a general problem of system identification by stochastic optimizaiton
with the covariance matrix adaption evolution strategy
this is a method which basically turns the optimizaiton problem into a learning
a distribution problem
first round is generated by a uniform distribution on a chosen space given by
2 tensors: search_space_size and search_space_centre which define the mean and range 
drawn from

each generation, there are no_samples_next_gen*no_samples_cycle children of which the best
no_samples_next_gen are chosen to parents the next generation
'''

class inverse_by_optimization:

    def __init__(self, loss, system, initial_inputs, initial_losses, no_samples_next_gen, no_samples_cycle):
        self.initial_inputs = initial_inputs
        self.initial_losses = initial_losses
        self.loss = loss
        self.system = system
        self.no_samples_next_gen = no_samples_next_gen
        self.no_samples_cycle = no_samples_cycle

    '''
    running optimization method
    choosing a benchmark loss value to stop at
    '''
    
    def run_optimization(self, bench_mark_loss):
        achieved_loss = float('inf')
        inputs = self.initial_inputs
        losses = self.initial_losses
        while ( achieved_loss > bench_mark_loss ) :
            print('next round')
            inputs, losses = self.previous_inputs_to_next( inputs, losses)
            achieved_loss = min(losses)

        achieved_index = losses.index(achieved_loss)
        return inputs[achieved_index]
    
    '''
    generates no_samples_cycle * no_samples_next_gen data 
    points with chosen random generator using inputs_previous and finds 
    a set of no_samples_next_gen of best points
    returns the set and corresponding losses

    !!! this code needs some optimization !!!
    '''
       
    def previous_inputs_to_next(self, inputs_previous, losses_previous):
        inputs_list = []
        losses_list = []
        for i in range (self.no_samples_next_gen):
            input_data = self.cma(inputs_previous, losses_previous)
            output_data = []
            for j in range (self.no_samples_cycle):
                output_data.append(self.system(input_data[j]).squeeze(0))
            output_data = torch.stack(output_data)
            best_input, best_loss = self.closest_output(input_data, output_data)
            print(f'offset {i+1} is {best_input} and has loss {best_loss.item()}')
            inputs_list.append(best_input)
            losses_list.append(best_loss.item())
        return inputs_list, losses_list

    ##### finds the input with smallest loss compared to true from a set  #####

    def closest_output(self, input_data, outputs):
        losses = self.loss(outputs)
        best_idx = torch.argmin(losses)
        best_input = input_data[best_idx]
        best_loss = losses[best_idx]
        return best_input, best_loss

    '''
    cma just takes previous stage data,
    and uses a weighting system (I chose 1/L) 
    to generate modified mean and variances of the data
    these then are used as inputs to a normal distribution
    to generate next stage
    source:
    https://arxiv.org/pdf/1604.00772

    '''  
        
    def cma(self, input_list, losses_list):
        offset_tensor = torch.stack(input_list)  #shape: (num,dim) 
        dim = offset_tensor.size(1) 
        #need to work in vectors here
        losses_tensor = torch.tensor(losses_list).unsqueeze(1)   #shape: (num,dim)
        #inverse loss as chosen weighting
        weights = torch.exp(-1*losses_tensor)
        weights = weights / weights.sum()
        #taking weighted mean
        offset_w_mean = torch.sum( offset_tensor * weights, dim = 0 ) #shape (dim)
        #covariance matrix accoring to source, equation 12
        offset_mean = torch.mean( offset_tensor, dim = 0 ) 
        unbiased_offset = (offset_tensor - offset_mean).unsqueeze(2) #shape (num,dim,1)
        unbiased_offset_t = unbiased_offset.transpose(1,2) #shape (num,1,dim)
        # |dim,1><1,dim| = dim,dim
        cov_elements = unbiased_offset @ unbiased_offset_t #shape (num,dim,dim)
        weights = weights.unsqueeze(1)
        cov = torch.sum(weights*cov_elements, dim = 0 ) #shape (dim,dim)
        #now sampling from a normal
        z = torch.randn(self.no_samples_cycle, dim)
        # and we use cholesky decomp to shape correct (LL^T = cov)
        L = torch.linalg.cholesky(cov)
        samples_out = offset_w_mean + z @ L.T
        return samples_out
    

  
